receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}

processors:
  batch:
    send_batch_size: 1024
    timeout: 5s

exporters:
  # zipkin:
  #   endpoint: "http://zipkin:9411/api/v2/spans"
  otlp/jaeger:
    endpoint: "jaeger:${env:OTEL_COLLECTOR_PORT_GRPC}"
    tls:
      insecure: true

extensions:
  zpages:
    endpoint: :55679

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]

