# OpenTelemetry Collector config that receives OTLP and exports to Zipkin
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        cors:
          allowed_origins:
          - "http://localhost:4000"
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}

processors:
  batch:
    send_batch_size: 1024
    timeout: 5s

exporters:
  otlp/jaeger:
    endpoint: "jaeger:${env:OTEL_COLLECTOR_PORT_GRPC}"
    tls:
      insecure: true

  debug:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1

extensions:
  zpages: {}

service:
  telemetry:
    logs:
      level: "debug"
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug]
